#!/bin/bash

[ -n "$DEBUG" ] && set -o xtrace
set -o errexit
shopt -s nullglob

BASE=nitrousio/autoparts-builder
now=$(date -u +"%d-%b-%Y-%H-%M")
commit=$1
pkg=$2
name="autoparts-${pkg}-${commit}-${now}"

docker run \
  -dns 8.8.8.8 \
  -v $(pwd):/home/action/.parts/autoparts \
  -w /home/action/.parts/autoparts \
  -name=$name \
  $BASE ./script/build.rb $commit $pkg
